services:
  database:
    image: postgres:17.5
    restart: unless-stopped

    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PORT: "${POSTGRES_PORT}"

    volumes:
      - db_data:/var/lib/postgresql/data
      # Optional tuned config:
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro

    ports:
      - "5432:5432"

    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5

    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
