import React from "react";
import {
  Html,
  Head,
  Preview,
  Body,
  Container,
  Section,
  Img,
  Text,
  Hr,
} from "@react-email/components";

export interface SyncSuccessEmailProps {
  /** Total events successfully synced */
  count: number;
  /** ISO date-time when the job completed */
  runAt: string;
}

/**
 * Beautiful, responsive transactional email that notifies the admin
 * whenever Webling → Prisma sync succeeds.
 *
 * ✅  Inline styles = bullet-proof across Gmail, Outlook, Apple Mail
 * ✅  Logo and brand colours
 * ✅  Accessible ALT text + logical heading order
 * ✅  Preview text for inbox glimpse  
 * ✅  Fallback text automatically generated by Resend
 */
export default function SyncSuccessEmail({ count, runAt }: SyncSuccessEmailProps) {
  const finished = new Date(runAt);
  const finishedLocal = finished.toLocaleString("en-GB", {
    timeZone: "Europe/Zurich",
    dateStyle: "medium",
    timeStyle: "short",
  });

  return (
    <Html>
      <Head />
      {/* What shows next to the subject in most inboxes */}
      <Preview>{`✅ ${count} events synced at ${finishedLocal}`}</Preview>

      <Body style={bodyStyle}>
        <Container style={cardStyle}>
          {/* Logo */}
          <Section style={logoSectionStyle}>
            <Img
              src="https://kyrios-badia.it/site/wp-content/uploads/2023/11/Kyrios_Sito_MobilLogo_2023_3.png"
              alt="Kyrios"
              width={120}
              height={32}
              style={{ display: "block", margin: "0 auto" }}
            />
          </Section>

          {/* Heading */}
          <Text style={h1Style}>Event sync completed</Text>

          {/* Body */}
          <Text style={pStyle}>
            Your calendar import from <strong>Webling</strong> finished at
            <br />
            <time dateTime={runAt}>{finishedLocal}</time>.
          </Text>

          <Text style={countStyle}>{count} events are now up-to-date.</Text>

          <Hr style={hrStyle} />

          <Text style={footerStyle}>
            You’re receiving this email because you enabled sync notifications
            in Kyrios. To turn them off, visit
            <a > Settings → Notifications</a>.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

// ========== Inline CSS (safe in >95% email clients) ==========
const bodyStyle: React.CSSProperties = {
  margin: 0,
  padding: "24px 16px",
  backgroundColor: "#f5f7fa",
  fontFamily: "Inter, Helvetica, Arial, sans-serif",
  color: "#111827",
};

const cardStyle: React.CSSProperties = {
  maxWidth: "500px",
  margin: "0 auto",
  backgroundColor: "#ffffff",
  borderRadius: "8px",
  padding: "32px 24px",
};

const logoSectionStyle: React.CSSProperties = { marginBottom: "24px" };

const h1Style: React.CSSProperties = {
  fontSize: "20px",
  fontWeight: 700,
  textAlign: "center",
  margin: "0 0 16px",
};

const pStyle: React.CSSProperties = {
  fontSize: "14px",
  lineHeight: "20px",
  margin: "0 0 12px",
  textAlign: "center",
};

const countStyle: React.CSSProperties = {
  fontSize: "16px",
  fontWeight: 600,
  textAlign: "center",
  margin: "0 0 24px",
  color: "#16a34a", // green-600
};

const hrStyle: React.CSSProperties = {
  border: "none",
  borderTop: "1px solid #e5e7eb", // gray-200
  margin: "32px 0",
};

const footerStyle: React.CSSProperties = {
  fontSize: "12px",
  lineHeight: "18px",
  color: "#6b7280", // gray-500
  textAlign: "center",
};
